version: '3.8'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application -w 2 -b :8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - redis

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
