# Generated by Django 4.2 on 2023-04-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetainingWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('top_breadth', models.FloatField()),
                ('base_breadth', models.FloatField()),
                ('Ka', models.FloatField()),
                ('gamma_soil', models.FloatField()),
                ('gamma_stone', models.FloatField()),
                ('surcharge', models.FloatField()),
                ('water_table', models.FloatField()),
                ('passive_soil_height', models.FloatField()),
                ('Kp', models.FloatField()),
            ],
        ),
    ]
